// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2421.Cerberus;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType; import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;
import edu.wpi.first.wpilibj.can.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Encoder roboSystemfrontLeftEnc;
    public static Encoder roboSystembackLeftEnc;
    public static Encoder roboSystemfrontRightEnc;
    public static CANJaguar roboSystemfrontLeft;
    public static CANJaguar roboSystembackLeft;
    public static CANJaguar roboSystemfrontRight;
    public static CANJaguar roboSystembackRight;
    public static CANJaguar roboSystemTote;
    public static Gyro roboSystemgyro;
    public static BuiltInAccelerometer roboSystemacc;
    public static Ultrasonic roboSystemUltrasonic1;
    public static Encoder roboSystembackRightEnc;
    public static DigitalInput toteTop;
    public static DigitalInput toteBottom;
    
    public static AnalogInput ultraSonic;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        roboSystemfrontLeftEnc = new Encoder(8, 9, false, EncodingType.k4X);
        LiveWindow.addSensor("roboSystem", "frontLeftEnc", roboSystemfrontLeftEnc);
        roboSystemfrontLeftEnc.setDistancePerPulse(1.0);
        roboSystemfrontLeftEnc.setPIDSourceParameter(PIDSourceParameter.kRate);
        roboSystembackLeftEnc = new Encoder(6, 7, false, EncodingType.k4X);
        LiveWindow.addSensor("roboSystem", "backLeftEnc", roboSystembackLeftEnc);
        roboSystembackLeftEnc.setDistancePerPulse(1.0);
        roboSystembackLeftEnc.setPIDSourceParameter(PIDSourceParameter.kRate);
        roboSystemfrontRightEnc = new Encoder(4, 5, false, EncodingType.k4X);
        LiveWindow.addSensor("roboSystem", "frontRightEnc", roboSystemfrontRightEnc);
        roboSystemfrontRightEnc.setDistancePerPulse(1.0);
        roboSystemfrontRightEnc.setPIDSourceParameter(PIDSourceParameter.kRate);
        roboSystemfrontLeft = new CANJaguar(2);
        
        
        roboSystembackLeft = new CANJaguar(3);
        
        
        roboSystemfrontRight = new CANJaguar(4);
        
        
        roboSystembackRight = new CANJaguar(5);
        
        
        roboSystemgyro = new Gyro(0);
        LiveWindow.addSensor("roboSystem", "gyro", roboSystemgyro);
        roboSystemgyro.setSensitivity(0.007);
        roboSystemacc = new BuiltInAccelerometer();
        LiveWindow.addSensor("roboSystem", "acc", roboSystemacc);
        roboSystemUltrasonic1 = new Ultrasonic(0, 1);
        LiveWindow.addSensor("roboSystem", "Ultrasonic 1", roboSystemUltrasonic1);
        
        roboSystembackRightEnc = new Encoder(2, 3, false, EncodingType.k4X);
        LiveWindow.addSensor("roboSystem", "backRightEnc", roboSystembackRightEnc);
        roboSystembackRightEnc.setDistancePerPulse(1.0);
        roboSystembackRightEnc.setPIDSourceParameter(PIDSourceParameter.kRate);
        
        ultraSonic = new AnalogInput(0);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        toteTop = new DigitalInput(1);
        toteBottom = new DigitalInput(2);
        roboSystemTote = new CANJaguar(9);
    }
}
