// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc2421.VictorTest.subsystems;

import com.sun.squawk.debugger.Log;
import org.usfirst.frc2421.VictorTest.RobotMap;
import org.usfirst.frc2421.VictorTest.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.can.CANTimeoutException;

import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class BallEject extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Victor passVictor = RobotMap.ballEjectpassVictor;
    DigitalInput rejected = RobotMap.ejected;
    DigitalInput done = RobotMap.reset;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public boolean enabled = true;
    
    public BallEject(){
        enabled &= (rejected != null);
        enabled &= (done != null);
        enabled &= (passVictor != null);
    }

    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }

    // TODO These should be more than just getters and setters. Subsystems
    // functions provide ways of controlling the subsystem without letting
    // outside users do everything by hand, as it were.
    public boolean getResetSwitch(){
        return done.get();
    }

    public boolean getFiredSwitch(){
        return rejected.get();
    }

    public void EjectArm(double speed){
         passVictor.set(speed);   
    }
    
    

    public void stopArm(){
            passVictor.set(0);
        }
    }

