// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc2421.Window.subsystems;
import org.usfirst.frc2421.Window.RobotMap;
import org.usfirst.frc2421.Window.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.can.*;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc2421.Window.Robot;
/**
 *
 */
public class Windows extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANJaguar victor = RobotMap.windowsVictor;
    DigitalInput limitSwitch1 = RobotMap.windowsLimitSwitch1;
    DigitalInput limitSwitch2 = RobotMap.windowsLimitSwitch2;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    public void setX(double speed) {
        victor.set(speed);
    }
    
    public boolean isBackPressed() {
        return limitSwitch1.get();
    }
    
    public boolean isFrontPressed(){
        return limitSwitch2.get();
    }
    
    public void eject(){
        Scheduler.getInstance().run();
        
        if (Robot.windows.isBackPressed() == true){
            Robot.windows.setX(-0.1);
        }
        
        if (Robot.windows.isFrontPressed() == true){
            Robot.windows.setX(0.1);
        }
    }
    
}
