// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc2421.Shu.subsystems;
import org.usfirst.frc2421.Shu.RobotMap;
import org.usfirst.frc2421.Shu.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.can.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class BigFireLeverSpring extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANJaguar leverReset = RobotMap.bigFireLeverSpringleverReset;
    AnalogChannel catapultAngle = RobotMap.bigFireLeverSpringfireSpringResetTest;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    //main static variables
    double motorSpeed;
    double motorResetVar;
    double motorSpring;
    
    public void resetSpring(){
        //check encoder
        //resets CJag motors to start position
        
        if (readEncoder() == 90){
            motorSpeed = -.5;
            try {
                leverReset.setX(motorSpeed);
            } catch (CANTimeoutException ex) {
                ex.printStackTrace();
            }
        }
        
        if (readEncoder() == 0){
            motorSpeed = 0;
            try {
                leverReset.setX(motorSpeed);
            } catch (CANTimeoutException ex) {
                ex.printStackTrace();
            }
        }
    }
    
    public double readEncoder(){
        return catapultAngle.getAverageVoltage() * 72;
        
    }
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}
