// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc2421.SimpleLauncher.commands;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.can.CANTimeoutException;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2421.SimpleLauncher.Robot;
/**
 *
 */
public class  catapultReset extends Command {
    
    public double motorSpeed = Robot.catapult.motorSpeed;
    public boolean finished = true;
    Joystick joystick = Robot.oi.getcatapultControl();
    
    public catapultReset() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.catapult);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        
        try {
            Robot.catapult.setX(-motorSpeed);
        } catch (CANTimeoutException ex) {
            ex.printStackTrace();
        }
                
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return finished;
    }
    // Called once after isFinished returns true
    protected void end() {
        
        try {
            Robot.catapult.setX(0);
        } catch (CANTimeoutException ex) {
            ex.printStackTrace();
        }
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
    
    protected void setFinished(boolean isFinished){
        finished = isFinished;
    }
    
}
