// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc2421.Apollo.subsystems;

import edu.wpi.first.wpilibj.CANJaguar;
import org.usfirst.frc2421.Apollo.RobotMap;
import org.usfirst.frc2421.Apollo.commands.*;
import edu.wpi.first.wpilibj.can.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class BallIntake extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANJaguar intakeMotor = RobotMap.ballIntakeintakeMotor;
    CANJaguar ballEjector = RobotMap.ballIntakeballEjector;
    
    public double spinnerSpeed = 1;
    public double ejectorSpeed = 1;
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    public void setIntakeSpeed(double speed) throws CANTimeoutException{
        intakeMotor.setX(speed);
    }
    
    public void setEjectSpeed(double speed)throws CANTimeoutException{
        ballEjector.setX(speed);
    }
    
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

