// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc2421.Apollo.subsystems;

import org.usfirst.frc2421.Apollo.RobotMap;
import org.usfirst.frc2421.Apollo.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType; 
//import edu.wpi.first.wpilibj.Encoder.PIDSourceParameter;
import edu.wpi.first.wpilibj.can.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Catapult extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANJaguar catMotor1 = RobotMap.catapultcatMotor1;
    CANJaguar catMotor2 = RobotMap.catapultcatMotor2;
    CANJaguar catMotor3 = RobotMap.catapultcatMotor3;
    DigitalInput upperLimit = RobotMap.catapultupperLimit;
    DigitalInput lowerLimit = RobotMap.catapultlowerLimit;
    Encoder catAngle = RobotMap.catAngle;
  
    public double fireSpeed = 1;
    public double reverseSpeed = -fireSpeed / 4;
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public void setX(double speed) throws CANTimeoutException{
        
        if(speed > 1){
            speed = 1;
        }
        if (speed < -1){
            speed = -1;
        }
        
        catMotor1.setX(speed);
        catMotor2.setX(speed);
        catMotor3.setX(speed);
    }
    
    
    public boolean lowerLimit(){
        return lowerLimit.get();
    }
    public boolean upperLimit(){
        return upperLimit.get();
    }
    
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

