// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2421.magEncoder.subsystems;

import org.usfirst.frc2421.magEncoder.RobotMap;
import org.usfirst.frc2421.magEncoder.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.can.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class driveMotors extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANJaguar leftMotor = RobotMap.driveMotorsleftMotor;
    CANJaguar rightMotor = RobotMap.driveMotorsrightMotor;
    Encoder magEncoder = RobotMap.driveMotorsmagEncoder;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public double distance = 1;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    
    public double encoderValue(){
        return magEncoder.getDistance();
    }
    public void setX(double speed){
        try {
            leftMotor.setX(speed);
            rightMotor.setX(speed);
        } catch(CANTimeoutException ex) {
            ex.printStackTrace();                 
        }
    }
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

