// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc2421.EncoderCatapult.subsystems;
import edu.wpi.first.wpilibj.CANJaguar;
import org.usfirst.frc2421.EncoderCatapult.RobotMap;
import org.usfirst.frc2421.EncoderCatapult.commands.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;import edu.wpi.first.wpilibj.Encoder;
 import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;
import edu.wpi.first.wpilibj.can.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class Catapult extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANJaguar jag1 = RobotMap.catapultjag1;
    CANJaguar jag2 = RobotMap.catapultjag2;
    Encoder magEncoder = RobotMap.catapultmagEncoder;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public double motorspeed = 0.25;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public void setX(double speed) throws CANTimeoutException{
        jag1.setX(speed);
        jag2.setX(speed);
    }
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}
