// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc2421.angleEncoder;
    
import edu.wpi.first.wpilibj.CANJaguar;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;
import edu.wpi.first.wpilibj.can.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANJaguar bigRedButtonCANJaguar1;
    public static Encoder bigRedButtonmagEncoder;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Encoder bigRedButtonmagEncoder2;
    public static CANJaguar bigRedButtonCANJaguar2;
    public static void init(){
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        try { 
            bigRedButtonCANJaguar1 = new CANJaguar(7);
        } catch (CANTimeoutException ex) {
            ex.printStackTrace();
        }
        try {
            bigRedButtonCANJaguar2 = new CANJaguar(3);
        } catch (CANTimeoutException ex) {
            ex.printStackTrace();
        }
	
        
        bigRedButtonmagEncoder = new Encoder(1, 3, 1, 1, false, EncodingType.k4X);
	LiveWindow.addSensor("bigRedButton", "magEncoder", bigRedButtonmagEncoder);
        bigRedButtonmagEncoder.setDistancePerPulse(18.84/360);//circumfrence / 360 = distance per pulse 
        bigRedButtonmagEncoder.setPIDSourceParameter(PIDSourceParameter.kDistance);
        bigRedButtonmagEncoder.start();
        
        bigRedButtonmagEncoder2 = new Encoder(1, 13, 1, 11, false, EncodingType.k4X);
        LiveWindow.addSensor("bigRedButton", "magEncoder", bigRedButtonmagEncoder2);
        bigRedButtonmagEncoder2.setDistancePerPulse(18.84/250);//circumfrence / 360 = distance per pulse 
        bigRedButtonmagEncoder2.setPIDSourceParameter(PIDSourceParameter.kDistance);
        bigRedButtonmagEncoder2.start();
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
