// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2421.DemoRobot.subsystems;

import org.usfirst.frc2421.DemoRobot.RobotMap;
import org.usfirst.frc2421.DemoRobot.commands.*;

import edu.wpi.first.wpilibj.CANJaguar;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.can.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Drive extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANJaguar leftMotor = RobotMap.driveleftMotor;
    CANJaguar rightMotor = RobotMap.driveRightMotor;
    CANJaguar backLeft = RobotMap.driveBackLeft;
    CANJaguar backRight = RobotMap.driveBackRight;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public Encoder enc = RobotMap.encoder;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public void leftSpeed(double speed){
    	leftMotor.set(speed);
    	backLeft.set(speed);
    }
    
    public void rightSpeed(double speed){
    	rightMotor.set(speed);
    	backRight.set(speed);
    }

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

