// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc2421.JoshPhotoelectric.subsystems;
import org.usfirst.frc2421.JoshPhotoelectric.RobotMap;
import org.usfirst.frc2421.JoshPhotoelectric.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.can.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class Photosensor extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANJaguar motor = RobotMap.photosensormotor;
    DigitalInput photoElectricSensor = RobotMap.photosensorphotoElectricSensor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
  //changes motor speed to specified variable
    public void setX(double speed) {
      try {
        motor.setX(speed);
      } catch (CANTimeoutException ex){
          
      }
          
    }
    
    
    
//sets motor speed based on light sensor state
    public void changeMotorState() {
        if (photoElectricSensor.get() == true) {
           setX(.1); 
        } else {
           setX(0);
        }
    }










// Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}
