// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2421.Cerberus.subsystems;

import org.usfirst.frc2421.Cerberus.RobotMap;
import org.usfirst.frc2421.Cerberus.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;
import edu.wpi.first.wpilibj.can.*;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class ToteLifter extends Subsystem {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	public double binSpeed = 1;
	public double toteSpeed = 1;

	//CANJaguar toteMotor = RobotMap.roboSystemTote;
	//CANJaguar binMotor = RobotMap.roboSystemBin;
	
	//public DigitalInput toteTop = RobotMap.toteTop;
	//public DigitalInput toteBottom = RobotMap.toteBottom;
	
	//public DigitalInput binTop = RobotMap.binTop;
	//public DigitalInput binBottom = RobotMap.binBottom;

	public void setToteLifter(double speed){
		RobotMap.roboSystemTote.set(speed);
		//toteMotor.set(speed);
	}

	public void setBinLifter(double speed){
		RobotMap.roboSystemBin.set(speed);
		//binMotor.set(speed);
	}
	
	@Override
	protected void initDefaultCommand() {
		// TODO Auto-generated method stub
		
	}
}
