// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2421.Cerberus.commands;

import org.usfirst.frc2421.Cerberus.Robot;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class  AutonomousCommand extends Command {
	boolean isFinished = false;
	Command bin = new LiftBin();
    public AutonomousCommand() {
    	
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize(){
    	isFinished = false;
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if(isFinished == false){
    		bin.start();
    		isFinished = true;
    		end();
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return isFinished;
    }

    // Called once after isFinished returns true
    @SuppressWarnings("deprecation")
	protected void end() {
    	Robot.lifter.setBinLifter(0);
    	//Robot.ServerThread.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @SuppressWarnings("deprecation")
	protected void interrupted() {
    	//Robot.ServerThread.stop();
    }
}
