// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc2421.angleEncoder.subsystems;
import edu.wpi.first.wpilibj.CANJaguar;
import org.usfirst.frc2421.angleEncoder.RobotMap;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.can.CANTimeoutException;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class bigRedButton extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public CANJaguar CANJaguar1 = RobotMap.bigRedButtonCANJaguar1;
    public CANJaguar CANJaguar2 = RobotMap.bigRedButtonCANJaguar2;
    public Encoder magEncoder = RobotMap.bigRedButtonmagEncoder;
    public Encoder magEncoder2 = RobotMap.bigRedButtonmagEncoder2;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public double speed = 0.1;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public void setX(double speed) throws CANTimeoutException{
        CANJaguar1.setX(speed);
        CANJaguar2.setX(speed);
    }
    
    public void controlMotorL(double speed) throws CANTimeoutException{
        CANJaguar2.setX(speed);
    }
    
    public void controlMotorR(double speed) throws CANTimeoutException{
        CANJaguar1.setX(speed);
    }
    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}
