// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc2421.EncoderAndBallIntake.subsystems;
import edu.wpi.first.wpilibj.CANJaguar;
import edu.wpi.first.wpilibj.Encoder;
import org.usfirst.frc2421.EncoderAndBallIntake.RobotMap;
import org.usfirst.frc2421.EncoderAndBallIntake.commands.*;
import edu.wpi.first.wpilibj.can.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class Catapult extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANJaguar catapultJag1 = RobotMap.catapultcatapultJag1;
    CANJaguar catapultJag2 = RobotMap.catapultcatapultJag2;
    CANJaguar catapultJag3 = RobotMap.catapultcatapultJag3;
    Encoder quadratureEncoder1 = RobotMap.catapultEncoder;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public double motorspeed = 0.25;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public void setX(double speed) throws CANTimeoutException{
        catapultJag1.setX(speed);
        catapultJag2.setX(speed);
        catapultJag3.setX(speed);
    }
    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}
