// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2421.Dalek.subsystems;

import org.usfirst.frc2421.Dalek.RobotMap;
import org.usfirst.frc2421.Dalek.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.can.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Eye_Stalk extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANJaguar eyeStalkJag = RobotMap.eye_StalkeyeStalkJag;
    DigitalInput eyeTop = RobotMap.eye_StalkeyeTop;
    DigitalInput eyeBottom = RobotMap.eye_StalkeyeBottom;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public double speed = 1;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public void setX(double speed) throws CANTimeoutException{
        eyeStalkJag.setX(speed);
    }
    
    public boolean getTop(){
        return eyeTop.get();
    }
    
    public boolean getBottom(){
        return eyeBottom.get();
    }

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

