// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2421.MecanumDrive.subsystems;

import org.usfirst.frc2421.MecanumDrive.RobotMap;
import org.usfirst.frc2421.MecanumDrive.commands.*;

import edu.wpi.first.wpilibj.CANJaguar;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.can.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Drive extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public CANJaguar motor1 = RobotMap.drivemotor1;
    public CANJaguar motor2 = RobotMap.drivemotor2;
    public CANJaguar motor3 = RobotMap.drivemotor3;
    public CANJaguar motor4 = RobotMap.drivemotor4;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
//    public Encoder encoder = new Encoder(1, 2);
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public void setMotor1(double speed){
    	motor1.set(speed);
    }
    
    public void setMotor2(double speed){
    	motor2.set(speed);
    }
    
    public void setMotor3(double speed){
    	motor3.set(speed);
    }
    
    public void setMotor4(double speed){
    	motor4.set(speed);
    }

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

