// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2421.Victors.subsystems;

import org.usfirst.frc2421.Victors.RobotMap;
import org.usfirst.frc2421.Victors.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc2421.Victors.Robot;


/**
 *
 */
public class Windows extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DigitalInput backSwitch = RobotMap.windowsbackSwitch;
    DigitalInput frontSwitch = RobotMap.windowsfrontSwitch;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Victor windowsVictor = RobotMap.windowsVictor;

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public void setX(double speed){
        windowsVictor.set(speed);
    }
    
    public boolean isFrontPressed(){
        return frontSwitch.get();
    }
    
    public boolean isBackPressed(){
        return backSwitch.get();
    }

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

